#Ankit Arora
#Planaria project. Read mapping and raw expression matrix were generated by CellRanger pipeline. [R version 4.0.3, Seurat_4.0.0]
set.seed(786)
setwd("/Users/Ankit/Desktop/Das_lab_post-doc_laptop/")

library(Seurat)
library(devtools)
library(ggplot2)
library(cowplot)

library(dplyr)
library(readxl)

library(stringi)
library(purrr)
library(reshape)


pathto.outPlots <- "/Users/Ankit/Desktop/Das_lab_post-doc_laptop/"
pathto.outData <- "/Users/Ankit/Desktop/Das_lab_post-doc_laptop/"
outName <- "scRNAseq_Planaria"


dirs <- list.dirs(path="/Users/Ankit/Desktop/Das_lab_post-doc_laptop/")
Gene_results_file_names <- dirs[ grepl("filtered_feature_bc_matrix", dirs) ]


#Read all the count files generated by Cell Ranger pipeline (in filtered_feature_bc_matrix folder)


test_data <- Read10X(data.dir = Gene_results_file_names[1])
Sample_name <- unlist(strsplit(Gene_results_file_names[1],"/"))[[7]]
ALL_WITH_COUNT <- as.data.frame(test_data)
colnames(ALL_WITH_COUNT) <- paste(colnames(ALL_WITH_COUNT),Sample_name, sep="_")
All_joined_countMatrixTemp <- (ALL_WITH_COUNT)
for (i in 2:length(Gene_results_file_names)){
cat("loop", i, "\n")
test_data <- Read10X(data.dir = Gene_results_file_names[i])
Sample_name <- unlist(strsplit(Gene_results_file_names[i],"/"))[[7]]
ALL_WITH_COUNT <- as.data.frame(test_data)
colnames(ALL_WITH_COUNT) <- paste(colnames(ALL_WITH_COUNT),Sample_name, sep="_")
All_joined_countMatrix <- cbind(All_joined_countMatrixTemp,ALL_WITH_COUNT)
All_joined_countMatrixTemp <- All_joined_countMatrix
}


#Read in the meta DATA info for all the samples/cell lines


metaDataOurs <-  data.frame(matrix(nrow=ncol(All_joined_countMatrix),ncol=2))
metaDataOurs[,1] <- colnames(All_joined_countMatrix)
metaDataOurs[,2] <- (sapply(stri_split_fixed(str = metaDataOurs[,1], pattern = "_", n = 2),"[[",2))
colnames(metaDataOurs)[1] <- "WholeID"
colnames(metaDataOurs)[2] <- "SampleID"
metaInfoAll <- metaDataOurs
rownames(metaInfoAll) <- metaInfoAll$WholeID


##Now we start with integeration analysis from Seurat

MTGplana <- CreateSeuratObject(All_joined_countMatrix, meta.data = metaInfoAll, min.cells = 100, min.features = 1000)


# Visualize QC metrics as a violin plot
VlnPlot(MTGplana, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
FeatureScatter(MTGplana, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
MTGplana.list <- SplitObject(iPSCsDopa, split.by = "SampleID")



##Store the fileterd object for later use for not integration analysis
MTGplana_WoInt <- MTGplana
for (i in 1:length(MTGplana.list)) {
MTGplana.list[[i]] <- SCTransform(MTGplana.list[[i]])
}


MTGplana.features <- SelectIntegrationFeatures(object.list = MTGplana.list, nfeatures = 3000)
MTGplana.list <- PrepSCTIntegration(object.list = MTGplana.list, anchor.features = MTGplana.features)




#reference.list <- iPSCsDopa.list[unique(metaInfoAll[,"SampleID"])]

#Take top 4 datset with highest number of cells
#reference_dataset <- match(names(tail(sort(table(iPSCsDopa$SampleID)),4)),names(reference.list))
#iPSCsDopa.anchors <- FindIntegrationAnchors(object.list = iPSCsDopa.list, normalization.method = "SCT",
#                                            anchor.features = iPSCsDopa.features, reference = reference_dataset)
   
MTGplana.anchors <- FindIntegrationAnchors(object.list = MTGplana.list, normalization.method = "SCT",
                                            anchor.features = MTGplana.features)                                      
MTGplana.integrated <- IntegrateData(anchorset = MTGplana.anchors, normalization.method = "SCT")

#rm(list = c('iPSCsDopa','iPSCsDopa.anchors','iPSCsDopa.list','reference.list'))

## Perform linear dimension reduction
MTGplana.integrated <- RunPCA(MTGplana.integrated, npcs = 30)

#MTGplana.integrated <- RunTSNE(MTGplana.integrated, nthreads = 40, max_iter = 2000, dims = 1:30)

MTGplana.integrated <- RunUMAP(MTGplana.integrated, dims = 1:30)


DefaultAssay(MTGplana.integrated) <- "integrated"
MTGplana.integrated <- FindNeighbors(MTGplana.integrated, reduction = "pca", dims = 1:30, nn.eps = 0.5)
MTGplana.integrated <- FindClusters(MTGplana.integrated, resolution = 0.1, n.start = 10)



############# Command to perform the visualization from Seurat object 


p2 <- DimPlot(MTGplana.integrated, reduction = "umap", label = TRUE)
pdf(paste(pathto.outPlots,"UMAP_integrated.pdf"), width=10, height=10)
plot_grid(p2)
dev.off()


p2 <- DimPlot(MTGplana.integrated, reduction = "umap", label = TRUE, split.by="SampleID")
pdf(paste(pathto.outPlots,"UMAP_integrated_SampleSplit.pdf"), width=10, height=10)
plot_grid(p2)
dev.off()

Idents(MTGplana.integrated) <- "SampleID"

p2 <- DimPlot(MTGplana.integrated, reduction = "umap", label = TRUE)


pdf(paste(pathto.outPlots,"UMAP_integrated_Samplewise.pdf"), width=10, height=10)
plot_grid(p2)
dev.off()


DefaultAssay(MTGplana.integrated) <- "RNA"


##  Normalise the data in RNA assay for plotting and differetial expression
MTGplana.integrated <- NormalizeData(MTGplana.integrated, verbose = FALSE)

##  Command to save the RDS object for future references
saveRDS(MTGplana.integrated,file = paste0(pathto.outData,outName,"_MTGplana.integrated.RDS"))


## Command to save the sessionInfo file
writeLines(capture.output(sessionInfo()), paste(pathto.outData,"sessionInfo.txt"))

#rm(list=setdiff(ls(), c("MTGplana.integrated","iPSCsDopa.markers")))


Idents(MTGplana.integrated) <- "seurat_clusters"

all_markers <-FindAllMarkers(MTGplana.integrated, 
                             min.pct =  0.1, 
                             min.diff.pct = 0.1, only.pos=TRUE)
							 
							 
## Command to write results into file
write.table(all_markers,file="all_markers.txt", sep="\t", quote=F,row.names=FALSE)	


## Command to read the SeuratObject 
MTGplana.integrated <- readRDS(file = "scRNAseq_Planaria_iPSCsDopa.integrated.RDS") 



## Command to make the heatmap of top 10 markers

all_markers %>%
group_by(cluster) %>%
top_n(n = 5, wt = avg_log2FC) -> top10
pdf(paste(pathto.outPlots,"Heatmap_top10.pdf"), width=10, height=10)
DoHeatmap(MTGplana.integrated, features = top10$gene) + NoLegend()
dev.off() 	



## Command to find markers between two groups (For example Lib_1 vs Lib_2)	

Idents(MTGplana.integrated) <- "SampleID"
cluster0_find_markers <- FindMarkers(MTGplana.integrated,min.pct =  0.1, ident.1 = Lib_1,ident.2=Lib_2,min.diff.pct = 0.1, only.pos=TRUE)
Lib_find_markers <- FindMarkers(MTGplana.integrated,min.pct =  0.1, ident.1 = "Lib_3",ident.2="Lib_4",min.diff.pct = 0.1, only.pos=TRUE)
write.table(cluster0_find_markers,file="/Users/Ankit/Desktop/Das_lab_post-doc/Lib_1_vs_Lib_2.txt", sep="\t", quote=F,row.names=FALSE)
write.table(Lib_find_markers,file="/Users/Ankit/Desktop/Das_lab_post-doc/Lib_3_vs_Lib_4.txt", sep="\t", quote=F,row.names=FALSE)



## Command to see the expression for particular gene

VlnPlot(MTGplana.integrated, features = c("SMESG000051024.1"))


## Command to see the UMAP plot for that particular gene

FeaturePlot(MTGplana.integrated, features = c("SMESG000051024.1"))	



## Command to get the head of any Seurat object 

MTGplana.integrated <- readRDS(file = "scRNAseq_Planaria_iPSCsDopa.integrated.RDS")
head(MTGplana.integrated@meta.data)						 





